on:
  push:
    branches:
      - main
name: Deploy
jobs:
  deploy:
    runs-on: [ remindcat-deploy-target ]
    steps:
      - name: Pull & Restart
        shell: bash
        run: |
          cd ~/remindcat
          GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa_remindcat_deploy" git pull
          poetry install --no-root
          sudo systemctl restart remindcat
